version: "3.8"
volumes:
  db:
    driver: local

networks:
  elastic:
   name: elastic
   external: true
  db:
    name: db
    external: true

services:
  app-server:
    image: ghcr.io/aml-afeka/app-server:latest
    restart: always
    ports: 
     - 4000:4000
    networks:
      - elastic
    environment:
      - SERVER_PORT=4000

      - DATABASE_SERVICE_URL=http://database-handler:5000
      - CLASSIFICATION_SERVICE_URL=http://${ADDR}:4002/

      - KIBANA_URL=http://elasticsearch:9200

  app-client:
    image: ghcr.io/aml-afeka/app-client:latest
    restart: always
    ports: 
     - 80:3000
    networks:
      - elastic
    environment:
      - FAST_REFRESH=false
      - SKIP_PREFLIGHT_CHECK=true

      - REACT_APP_SETTINGS_URL=http://${ADDR}:81

      - REACT_APP_GRAPHQL_URL=http://${ADDR}:4000/

      - REACT_APP_DASHBOARD_KIBANA_URL=http://${ADDR}:5601/app/canvas#/workpad/workpad-00c1e6f9-9128-412c-9d72-bc939f03b4d0/page/1?__fullScreen=true
      
    depends_on:
      - app-server

  app-maintenance:
    image: ghcr.io/aml-afeka/app-maintenance:latest
    restart: always
    ports: 
     - 81:3030
    networks:
      - elastic
    environment:
      - PORT=3030

      - FAST_REFRESH=false
      - SKIP_PREFLIGHT_CHECK=true

      - REACT_APP_GRAPHQL_URL=http://${ADDR}:4000/
      - REACT_APP_KIBANA_URL="http://${ADDR}:5601"
      - REACT_APP_CLIENT_URL="http://${ADDR}:80"
      - REACT_APP_GIT_URL="https://github.com/AML-AFEKA"
    depends_on:
      - app-server


  database-handler:
    image: ghcr.io/aml-afeka/database-handler:latest
    restart: always
    ports: 
    - 5000:5000
    networks:
      - elastic
      - db
    environment:
      - SERVICE_PORT=5000

      - GRAPHQL_URL=http://app-server:4000/

      - MONGODB_URL=mongodb://${ADDR}:27017/amldb

      - KIBANA_URL=http://elasticsearch:9200
    depends_on:
      - app-server

  # classification:
  #   image: ghcr.io/aml-afeka/classification:latest
  #   restart: always
  #   ports: 
  #   - 4002:4002
  # networks:
  #   - elastic
  #   environment:
  #     - SERVICE_PORT=4002

  #     - GRAPHQL_URL=http://app-server:4000/
  #     - KIBANA_URL=http://elasticsearch:9200
  #   depends_on:
  #     - app-server