version: "3.8"
volumes:
  db:
    driver: local

networks:
 elastic:
   name: elastic
   external: true

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    restart: always
    ports:
      - 5601:5601
    networks:
      - elastic
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GOSU_VERSION=1.17
      - JSYAML_VERSION=3.13.1
      - MONGO_PACKAGE=mongodb-org
      - MONGO_REPO=repo.mongodb.org
      - MONGO_MAJOR=7.0
      - MONGO_VERSION=7.0.8
      - HOME=/data/db
    volumes:
      - db:/data/configdb
      - db:/data/db

  app-server:
    image: ghcr.io/aml-afeka/app-server:latest
    restart: always
    ports: 
     - 4000:4000
    environment:
      - SERVER_PORT=4000

      - DATABASE_SERVICE_URL=http://database-handler:5000
      - CLASSIFICATION_SERVICE_URL=http://classification:4002/

      - KIBANA_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  app-client:
    image: ghcr.io/aml-afeka/app-client:latest
    restart: always
    ports: 
     - 80:3000
    environment:
      - FAST_REFRESH=false
      - SKIP_PREFLIGHT_CHECK=true

      - REACT_APP_GRAPHQL_URL=http://${ADDR}:4000/

      - REACT_APP_DASHBOARD_KIBANA_URL=http://${ADDR}:5601/app/canvas#/workpad/workpad-33aa87e5-fc5e-43dd-938e-1f145a0ffb5f/page/1?__fullScreen=true
    depends_on:
      - app-server

  app-maintenance:
    image: ghcr.io/aml-afeka/app-maintenance:latest
    restart: always
    ports: 
     - 81:3030
    environment:
      - PORT=3030

      - FAST_REFRESH=false
      - SKIP_PREFLIGHT_CHECK=true

      - REACT_APP_GRAPHQL_URL=http://${ADDR}:4000/
    depends_on:
      - app-server


  database-handler:
    image: ghcr.io/aml-afeka/database-handler:latest
    restart: always
    ports: 
    - 5000:5000
    environment:
      - SERVICE_PORT=5000

      - GRAPHQL_URL=http://app-server:4000/

      - MONGODB_URL=mongodb://mongodb:27017/amldb

      - KIBANA_URL=http://elasticsearch:9200
    depends_on:
      - mongodb
      - app-server

  classification:
    image: ghcr.io/aml-afeka/classification:latest
    restart: always
    ports: 
    - 4002:4002
    environment:
      - SERVICE_PORT=4002

      - GRAPHQL_URL=http://app-server:4000/
      - KIBANA_URL=http://elasticsearch:9200
    depends_on:
      - app-server